language: node_js
node_js:
  - lts/*
install:
  - pnpm install # npm ci
script:
  - pnpm run build
deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  local_dir: dist
  repo: amelia-coding/amelia-coding.github.io
  # github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  github_token: $REPO_TOKEN
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: mmJocOi2tCNdI2dFgXnhSVZlmzL5TPi3XP1JYx6BDcF65It0SpX8dHpJeliLlQsuLrASUrmpTF+z7ayzpM2tE8fgDqcORYAel5ZEUU5T4PQrZqLhkV3iRtc6EdJ/sKPBIZkDP7tHNhORs3cytWKDEJMalfxOrNzlUrJXC4PrszfrIaGukafZgLiSrdE15mWsg/wCZtMaaDlLghEnAWvkGDv9Jzxf1z7aoqBKah18c5NpZvwbu/ynjiD4Qd7sTqNXwyzoqeC6/i4Peu1gV6MDgF3E6RjOa5RQ2qudvdJRUjUEKuH5N+u8mi3OzUARjmm5Zbi7Ctxbk+yCGkrv8TRyi3SLxsXHrskDbV1Uh359PaAjn06i1HPFwhXWA80AceDT5RBScctwJnh6p1PiG+Equ3OvYEf93jTDQtURALFhjFKdTQgeStbw7UsjZWZGyCkj/+G+Z9I2A6Ohg3BGaqSanof+oeiY6o1HAEIwmD7309E0oib3aBv8NBao+5R43UJW40+RA4Fr2ovh34n74ucn3pkR1TUW3yV5XiFtliMovkGl2Rh0dZ2bRj/sOSuly2wY9Xa9kKHYDj8X4bOgiyFHK2X9jPcNj2RFc/mPyON2QlZ/pCi+JQK2Pwbq58POWJR/8n2ySYkKGPxJrs6QOE1SNao30s0oqKkcrfJw39yt5G8=
