name: github pages

on:
  push:
    branches: 
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
     
    - name: Use Node.js 16.x  
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
      
    - name: deploy blog gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist

    - name: deploy
      # 该 Action 可以将当前仓库指定的某个目录下的文件上传到另一个仓库
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:amelia-coding/amelia-coding.github.io.git
        BRANCH: master
        # 该目录都会上传到repo仓库
        FOLDER: dist
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}