name: github pages

on:
  push:
    branches: 
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
     
    - name: Use Node.js 16.x  
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'pnpm'

    - name: build
      run: pnpm install
      run: pnpm run build
      
    - name: deploy amelia-coding.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN  }}
        EXTERNAL_REPOSITORY: amelia-coding/amelia-coding.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: dist